# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-28 20:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='draft',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='publish',
            field=models.DateField(default=datetime.datetime(2017, 1, 28, 20, 10, 27, 782587, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
